### ISSUE TITLE
Publish to Hex.pm

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [miniclip/poolgirl#10]
`poolgirl` [already exists](https://hex.pm/packages/poolgirl), unfortunately. We'd probably have to pick a different name 😢.

**Comment by g-andrade** [comment]
Perhaps we can name the package `mc_poolgirl` (while keeping the application name as is.)

**Comment by g-andrade** [comment]
Alternatively, we may also pick `poolgurl` if we want to get sassy.
